### ISSUE TITLE
Hosting Platform

### ISSUE THREAD

**Issue by Rithy58** [ODDEngineering/AnalMyList#7]
So for hosting the app, I'm highly considering Heroku.

Other options are AWS, Kubernetes, Azure, and Google Cloud. Let me know if you have any strong feelings, otherwise, I'm signing us up for Heroku.

Current plan:
Use Nginx buildpack to serve webapp static files and API server
Use redis addon for queue
Use workers to process queue

**Comment by Meltaman** [comment]
No, I don't have any strong feelings in any particular way.
